### ISSUE TITLE
tk and tcl dependencies

### ISSUE THREAD

**Issue by beroal** [MTG/sms-tools#116]
While `README.md` specifies dependencies for `sms-tools` like `matplotlib`, it misses `tk` and `tcl`. Without both, I get
```
python models_GUI.py
```
```
Traceback (most recent call last):
  File "/home/user/prg/gitclone/sms-tools/software/models_interface/models_GUI.py", line 6, in <module>
    from Tkinter import *   ## notice capitalized T in Tkinter 
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/prg/gitclone/sms-tools/software/models_interface/models_GUI.py", line 9, in <module>
    from tkinter import *   ## notice lowercase 't' in tkinter here
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```

Without `tcl`, but with `tk`, I get
```
python models_GUI.py
```
```
Traceback (most recent call last):
  File "/home/user/prg/gitclone/sms-tools/software/models_interface/models_GUI.py", line 6, in <module>
    from Tkinter import *   ## notice capitalized T in Tkinter 
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/prg/gitclone/sms-tools/software/models_interface/models_GUI.py", line 9, in <module>
    from tkinter import *   ## notice lowercase 't' in tkinter here
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtcl8.6.so: cannot open shared object file: No such file or directory
```
ArchLinux, Python 3.9.1.

**Comment by alexsivris** [comment]
This solution from SO worked for me on macOS Big Sur 11.3: https://stackoverflow.com/a/55651778
