### ISSUE TITLE
models_GUI.py and models_transformations_GUI.py don't run in python3

### ISSUE THREAD

**Issue by jure2018** [MTG/sms-tools#132]
Workaround: run the GUIs in python 2 (I have 2.7.16 and both GUIs work in python2).

Env: macOS 11.6.6
python3: 3.10.5

Error message:
> python3 models_GUI.py

Traceback (most recent call last):
  File "/Users/one/Music/DigitalAudioWork/Coursera/AudioSignalProcessing/sms-tools-master/software/models_interface/models_GUI.py", line 23, in <module>
    nb = notebook(root, TOP) # make a few diverse frames (panels), each using the NB as 'master': 
  File "/Users/one/Music/DigitalAudioWork/Coursera/AudioSignalProcessing/sms-tools-master/software/models_interface/notebook.py", line 12, in __init__
    self.choice = IntVar(0) 
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 564, in __init__
    Variable.__init__(self, master, value, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'int' object has no attribute '_root'

********
I realize macOS isn't supported and I am on a more recent version of python3.  So I don't expect a response, but I'm posting here for reference in case future work on sms-tools is done. Also, for others who may experience this error.

**Comment by mohsen796** [comment]
This is the problem with the scipy. some imports have been changed in the new version.
you can see the changes in [link](https://github.com/MTG/sms-tools/commit/fca2c511eb7d77333c92e15888a2904f1b705185).
I am unsure if all the functions work as expected with the new imports, but they should be fine.

**Comment by xserra** [comment]
fixed
