### ISSUE TITLE
Cannot compile functions in C

### ISSUE THREAD

**Issue by juliedelisle5** [MTG/sms-tools#38]
Hi everyone,
I am trying to install and use the sms-tools on Mac OS X 10.6.8. I previously had installed Anaconda on my computer, to get all necessary modules for the sms-tools. I get stuck at the compilation of the functions in C, after which I get this error:

MacBook-Pro-de-Julie-Delisle:utilFunctions_C juliedelisle$ python compileModule.py build_ext --inplace
Traceback (most recent call last):
  File "compileModule.py", line 5, in <module>
    import numpy
  File "/Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/**init**.py", line 184, in <module>
    from . import add_newdocs
  File "/Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/lib/**init**.py", line 8, in <module>
    from .type_check import *
  File "/Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: dlopen(/Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/core/multiarray.so, 10): Symbol not found: _strnlen
  Referenced from: /Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/core/../../../..//libmkl_intel_lp64.dylib
  Expected in: flat namespace
 in /Users/juliedelisle/anaconda/lib/python2.7/site-packages/numpy/core/../../../..//libmkl_intel_lp64.dylib

Have anyone experienced this? How can I fix this?
Thanks!

**Comment by juliedelisle5** [comment]
Issue solved - I am now able to run the GUI !
I think the problem was due to the fact that I was using Python 2.7.12 in my virtual environment. There is apparently a conflict with the C libraries used in this version (found out after some research on StackOverflow with "Symbol not found: _strnlen").
The solution was to create a new virtual environment with Python 2.7.9, which works fine with the sms-tools. Of course, be sure to have installed Anaconda for Python 2.7.

Here is a step by step tutorial for the installation of the sms-tools on Mac OS X that worked for me:
http://flothesof.github.io/sms-tools-MacOSX-Anaconda.html

See also the conda documentation about managing environments and packages, if you are not familiar with the topic (as I was before writing this): http://conda.pydata.org/docs/using/using.html
