### ISSUE TITLE
Cannot compile C functions

### ISSUE THREAD

**Issue by rameshkaturi** [MTG/sms-tools#43]
karthik@kaka:~/learning/audio_signal_processing/sms-tools-master/software/models/utilFunctions_C$ python compileModule.py build_ext --inplace
Traceback (most recent call last):
  File "compileModule.py", line 5, in <module>
    import numpy
  File "/home/karthik/.local/lib/python2.7/site-packages/numpy/**init**.py", line 180, in <module>
    from . import add_newdocs
  File "/home/karthik/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/karthik/.local/lib/python2.7/site-packages/numpy/lib/**init**.py", line 8, in <module>
    from .type_check import *
  File "/home/karthik/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/karthik/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /home/karthik/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: _PyUnicodeUCS4_IsWhitespace

Can someone help me to fix this issue?

**Comment by EMCP** [comment]
did you try `python3 compile...` by chance? worked for me
