### ISSUE TITLE
numpy booleans are not JSON serializable

### ISSUE THREAD

**Issue by DavidAntliff** [MTG/sms-tools#51]
If a numpy function that returns a numpy boolean such as `np.all()` is used, such as in A3Part3 where `isRealEven` is calculated and returned, the JSON serialization in `submit.py` will fail with the error:

```Please enter which part you want to submit (1-4 or all): 3
Traceback (most recent call last):
  File "submitA3.py", line 309, in <module>
    submit()
  File "submitA3.py", line 56, in submit
    rep = submitSolution(email, password, output(partIdx), partIdx)
  File "submitA3.py", line 274, in output
    outputString += convertNpObjToStr(ans) + '\n'
  File "submitA3.py", line 209, in convertNpObjToStr
    return json.dumps(obj)
  File "/home/.../.pyenv/versions/2.7.13/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/home/.../.pyenv/versions/2.7.13/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/.../.pyenv/versions/2.7.13/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/.../.pyenv/versions/2.7.13/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: True is not JSON serializable
```
One workaround seems to be to convert `isRealEven` to a Python bool with `isRealEven = bool(np.all(...))`.

**Comment by csaftoiu** [comment]
this will fix it as well:

```
class CustomJSONEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.bool_):
            return super(DateTimeJSONEncoder, self).encode(bool(obj))

        return super(DateTimeJSONEncoder, self).default(obj)
```

And then:

```
json.dump(obj, f, cls=CustomJSONEncoder)
```

**Comment by tszwangkwong** [comment]
Where is DateTimeJSONEncoder?

**Comment by HarmC** [comment]
He renamed his class later. Everywhere where it says DateTimeJSONEncoder, it should say CustomJSONEncoder
