### ISSUE TITLE
Submission First assignement

### ISSUE THREAD

**Issue by Nicolas-Rieu** [MTG/sms-tools#77]

**Comment by Nicolas-Rieu** [comment]
Hi, I don't succeed to submit my work
---------------------------------------------------------------------------------------------------
== Once your parts are correct, you have to submit them all at once by entering "all"
Please enter which part you want to submit (1-3 or all): 1
Traceback (most recent call last):
  File "D:\Nicolas Rieu\Documents\UTC\Cours en ligne\Coursera\sms-tools-master\assignments\A1\A1_2017\A1\submitA1.py", line 285, in <module>
    submit()
  File "D:\Nicolas Rieu\Documents\UTC\Cours en ligne\Coursera\sms-tools-master\assignments\A1\A1_2017\A1\submitA1.py", line 56, in submit
    rep = submitSolution(email, password, output(partIdx), partIdx)
  File "D:\Nicolas Rieu\Documents\UTC\Cours en ligne\Coursera\sms-tools-master\assignments\A1\A1_2017\A1\submitA1.py", line 254, in output
    answer = readAudio(**line)
  File "D:\Nicolas Rieu\Documents\UTC\Cours en ligne\Coursera\sms-tools-master\assignments\A1\A1_2017\A1\A1Part1.py", line 49, in readAudio
    (fs, x) = read(inputFile)
  File "D:\Anaconda\lib\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../../sounds/oboe-A4.wav'
------------------------------------------------------------------------------------------------------
do you have an idea to debug it ?
